let cities = [
    "London",
    "Paris",
    "New York",
    "Tokyo",
    "Dubai",
    "Barcelona",
    "Rome",
    "Madrid",
    "Singapore",
    "Amsterdam",
    "Prague",
    "Los Angeles",
    "Chicago",
    "San Francisco",
    "Berlin",
    "Hong Kong",
    "Washington",
    "Beijing",
    "Dublin",
    "Istanbul",
    "Las Vegas",
    "Budapest",
    "Toronto",
    "Sydney",
    "Seoul",
    "Doha",
    "Abu Dhabi",
    "Osaka",
    "Bangkok",
    "Vienna",
    "San DIego",
    "Zurich",
    "Boston",
    "Lisbon",
    "Warsaw",
    "Seattle",
    "Atlanta",
    "Stockholm",
    "Miami",
    "Athens",
    "Rio de Janeiro",
    "Montreal",
    "Brussels",
    "Tel Aviv",
    "Oslo",
    "Mumbai",
    "Shanghai",
    "Lyon",
    "Bilbao",
    "Liverpool",
    "Manchester",
    "Jerusalem",
    "Minsk",
    "Jakarta",
    "Gothenburg",
    "Glasgow"
]

module.exports = cities;
